---

- name: add epel repo
  yum:
    name: "{{ epel }}"
    state: present

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started

- name: set nginx load balancer
  template:
    src: application.conf
    dest: /etc/nginx/conf.d/application.conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
